# Site settings
title: Re-Al Dev World
description: 'Un blog de R. Alonzo Vera A.'
url: 'https://re-al-7.github.io/'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Alonzo Vera A.'
  email: 7.re.al.7@gmail.com
  twitter_username: re_al_
  facebook_username: real
  github_username:  re-al-7
  linkedin_username:  'real7'

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
